### ISSUE TITLE
Equirectangular output? 

### ISSUE THREAD

**Issue by NickNothom** [matheowis/HDRI-to-CubeMap#5]
Hello, this project is awesome!

Would it be possible to add a simple equirectangular output as png or jpg? 

Right now this site is the only way I can successfully open .hdr files from HDRIHaven, and it would be great if I could just use this tool to convert them to .jpg or .png, while keeping it equirectangular.

**Comment by matheowis** [comment]
Hi, have you tried https://onlineconvertfree.com/convert-format/hdr-to-jpg/ ?
