### ISSUE TITLE
Saving as hdr fails

### ISSUE THREAD

**Issue by FutureFireplace** [matheowis/HDRI-to-CubeMap#9]
Hello

 - great app, but I can only use the .png save/export.
 When using .hdr the only image output comes from the original image (small italian summer street)

//br

**Comment by matheowis** [comment]
Hi @FutureFireplace, I tried to reproduce it, but everything works fine on my end.

Maybe you are importing non hdr file, thats the only way i could get the same results as you, hdr file contains more information then png or jpg, this app does not support conversions from (png or jpg) to hdr

**Comment by FutureFireplace** [comment]
ok, I get it, thanks ... it might have confused me that png-to-png or jpg-to-jpg worked
